In [1]:
import torch
import torch.nn as nn

In [7]:
lstm_cell = nn.LSTMCell(2, 10)
lstm = nn.LSTM(2, 10, batch_first=True)

In [8]:
print("LSTM Cell")
for param in lstm_cell.parameters():
    print(param.shape)
    param.data.fill_(1)

    
print("LSTM")
for param in lstm.parameters():
    print(param.shape)
    param.data.fill_(1)

LSTM Cell
torch.Size([40, 2])
torch.Size([40, 10])
torch.Size([40])
torch.Size([40])
LSTM
torch.Size([40, 2])
torch.Size([40, 10])
torch.Size([40])
torch.Size([40])


In [9]:
t = torch.randn(1, 1, 2)

In [19]:
o1, (h1, c1) = lstm(t)

In [20]:
o1.shape, h1.shape, c1.shape

(torch.Size([1, 1, 10]), torch.Size([1, 1, 10]), torch.Size([1, 1, 10]))

In [21]:
o2, h2 = lstm_cell(t[:, 0])

In [22]:
o2.shape, h2.shape

(torch.Size([1, 10]), torch.Size([1, 10]))

In [23]:
o1, o2

(tensor([[[-0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595,
           -0.0595, -0.0595, -0.0595]]], grad_fn=<TransposeBackward0>),
 tensor([[-0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595,
          -0.0595, -0.0595]], grad_fn=<MulBackward0>))

(tensor([[[-0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595, -0.0595,
           -0.0595, -0.0595, -0.0595]]], grad_fn=<StackBackward0>),
 tensor([[-0.1477, -0.1477, -0.1477, -0.1477, -0.1477, -0.1477, -0.1477, -0.1477,
          -0.1477, -0.1477]], grad_fn=<AddBackward0>))